/*
 * API Farmacia ITQ - Sistema de Gestión Integral
 * API REST para la gestión de medicamentos, empleados y ventas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: farmacy@queretaro.tecnm.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.farmacy.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;


/**
 * MedicationPatch
 */
@JsonPropertyOrder({
  MedicationPatch.JSON_PROPERTY_MEDICATION_NAME,
  MedicationPatch.JSON_PROPERTY_CONTENT,
  MedicationPatch.JSON_PROPERTY_PRICE,
  MedicationPatch.JSON_PROPERTY_EXPIRATION_DATE,
  MedicationPatch.JSON_PROPERTY_IN_STOCK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T07:58:18.178356800-06:00[America/Mexico_City]")
public class MedicationPatch {
  public static final String JSON_PROPERTY_MEDICATION_NAME = "medicationName";
  private String medicationName;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private BigDecimal content;

  public static final String JSON_PROPERTY_PRICE = "price";
  private BigDecimal price;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  private LocalDate expirationDate;

  public static final String JSON_PROPERTY_IN_STOCK = "inStock";
  private Boolean inStock;

  public MedicationPatch() {
  }

  public MedicationPatch content(BigDecimal content) {
    this.content = content;
    return this;
  }

  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getContent() {
    return content;
  }

  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(BigDecimal content) {
    this.content = content;
  }

  public MedicationPatch inStock(Boolean inStock) {
    this.inStock = inStock;
    return this;
  }

  @JsonProperty(JSON_PROPERTY_IN_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getInStock() {
    return inStock;
  }

  @JsonProperty(JSON_PROPERTY_IN_STOCK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInStock(Boolean inStock) {
    this.inStock = inStock;
  }

  public MedicationPatch medicationName(String medicationName) {
    this.medicationName = medicationName;
    return this;
  }

   /**
   * Get medicationName
   * @return medicationName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MEDICATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMedicationName() {
    return medicationName;
  }


  @JsonProperty(JSON_PROPERTY_MEDICATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedicationName(String medicationName) {
    this.medicationName = medicationName;
  }


  public MedicationPatch price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public MedicationPatch expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getExpirationDate() {
    return expirationDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }


  /**
   * Return true if this MedicationPatch object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MedicationPatch medicationPatch = (MedicationPatch) o;
    return Objects.equals(this.medicationName, medicationPatch.medicationName) &&
        Objects.equals(this.price, medicationPatch.price) &&
        Objects.equals(this.expirationDate, medicationPatch.expirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(medicationName, price, expirationDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MedicationPatch {\n");
    sb.append("    medicationName: ").append(toIndentedString(medicationName)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `medicationName` to the URL query string
    if (getMedicationName() != null) {
      joiner.add(String.format("%smedicationName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMedicationName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format("%sprice%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrice()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `expirationDate` to the URL query string
    if (getExpirationDate() != null) {
      joiner.add(String.format("%sexpirationDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpirationDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

